name: Swarmpit Deploy Pipeline

on:
    workflow_call:
        inputs:
            project_name:
                description: "Project name in Swarmpit"
                required: true
                type: string

jobs:
    deploy:
        runs-on: [builder]
        steps:
            - uses: actions/checkout@v4
            - name: Deploy using Swarmpit
              run: |
                  curl -X POST -sSL -H "authorization: ${{ secrets.SWARMPIT_BEARER }}" "${{ secrets.SWARMPIT_BASE_URL }}/stacks/${{ inputs.project_name }}/redeploy"
